QTL contains undefined functions
Gilead-BioStats/gsm pull request #1403
Opened 2023-11-10 18:24 UTC by andersonjake1988

## Overview
fix #1391 

## Test Notes/Sample Code

Notes:

2023-11-13 20:18 UTC, mattroumaya requested changes
I'm not able to run the QTL report with a local installation of this branch by running: 

```
library(gsm)

snapshot <- gsm::Make_Snapshot()

gsm::Study_Report(snapshot, strReportType = "QTL")
```
I'm getting the error:

```
Output created: gsm_country_report.html
> gsm::Study_Report(snapshot, strReportType = "QTL")


processing file: KRIReportByQTL.Rmd
  |...................................................                                      |  57% [unnamed-chunk-4]
Quitting from lines 54-65 [unnamed-chunk-4] (KRIReportByQTL.Rmd)
Error in `is.data.frame()`:
! object 'results_summary' not found
Backtrace:
 1. gsm::qtl_results(setup$active)
 5. dplyr:::left_join.data.frame(., results_summary)
 6. dplyr::auto_copy(x, y, copy = copy)
 8. dplyr:::same_src.data.frame(x, y)
 9. base::is.data.frame(y)
```

2023-11-13 20:18 UTC, mattroumaya commented on gsm_QTL_report.html
I've done this so many times, but make sure to delete this

2023-11-13 22:48 UTC, andersonjake1988 commented on gsm_QTL_report.html
I knew it would happen one day, thanks for catching it!

2023-11-15 22:48 UTC, mattroumaya approved these changes
Excellent! 😎

2023-11-15 22:48 UTC, merged