v2 Qualification Test Updates
Gilead-BioStats/gsm pull request #1615
Opened 2024-06-28 16:33 UTC by andersonjake1988

## Overview
IN WORK:
qual tests

Notes:

2024-07-22 15:09 UTC, andersonjake1988 commented
In the case of NA values for GroupID the data pipeline breaks down at the Transform_Rate step, which has a stop clause for that situation. I have incorporated logic in the Input_Rate step to filter out cases of NA GroupID and informing the user how many cases there were when processing the yaml

2024-07-22 15:22 UTC, lauramaxwell commented
sounds good, @andersonjake1988. Can you make sure this branch is up to date with `dev` so that we are testing the most recent versions of the functions, and any edits to the codebase won't lead to conflicts when we try to get this merged in?

2024-07-25 15:30 UTC, andersonjake1988 commented
# NOTES:
- not sure if there is a reason, but I noticed the yamls for kri's and cou's 6, 7, and 12 have a nMinDenominator of 3 when everything else has 30.

2024-07-25 18:06 UTC, lauramaxwell requested changes
looking good! a few questions and edits and we should be gtg soon!

2024-07-25 20:53 UTC, andersonjake1988 commented on R/Input_Rate.R
> +#'     dfSubjects = clindata::rawplus_dm,
I this added logic into the end to check for NA `GroupID` 
`if(any(is.na(dfInput$GroupID))){
        cli_alert_warning(glue::glue("{sum(is.na(dfInput$GroupID))} cases of NA's in GroupID, cases are removed in output"))
        dfInput <- dfInput %>%
            filter(!is.na(.data$GroupID))
    }`

2024-07-25 20:57 UTC, andersonjake1988 commented on inst/longitudinal_demo/LongitudinalReport.R
> +devtools::load_all()
sorry it slipped through the cracks when I was merging dev, I will delete it

2024-07-25 20:57 UTC, andersonjake1988 commented on inst/qualification/qualification_specs.csv
> +1,1,T1_1,mapping.yaml,"lData is correctly mapped for processing using ""mapping.yaml"" in conjunction with `MakeWorkflowList()` and `RunWorkflow`",High,High,Awaiting Approval,,In progress,
good catch I will update it

2024-07-26 07:21 UTC, lauramaxwell commented on R/Input_Rate.R
> +#'     dfSubjects = clindata::rawplus_dm,
great- thanks!

2024-07-26 09:58 UTC, lauramaxwell commented
These qual tests all pass, and are appropriate, but since each file contains more than one test, the qualification report does not render properly. Since tests are run in an `imap`, there isn't a way to separate the test files, but I want to be able to account for each individual test. I know there some tweaks i need to make to the Qualification.Rmd, but see screenshot below for what i'm talking about - 24 tests and 311 tests pass... @jwildfire 

![image](https://github.com/user-attachments/assets/8bd0d2b9-fb25-4457-8de2-bacc256190d6)

2024-07-26 11:42 UTC, jwildfire commented
> These qual tests all pass, and are appropriate, but since each file contains more than one test, the qualification report does not render properly. Since tests are run in an `imap`, there isn't a way to separate the test files, but I want to be able to account for each individual test. I know there are some tweaks i need to make to the Qualification.Rmd, but see screenshot below for what i'm talking about - 24 tests and 311 tests pass... @jwildfire

Agreed. We'll want these split out into multiple line items in the report.

2024-07-26 15:06 UTC, lauramaxwell commented
qualification report is fixed! will merge in shortly :)

2024-07-26 15:50 UTC, lauramaxwell commented
QualificationWorkflow.Rmd still needs a bit of work. hoping to be able to get it done quickly

2024-07-26 16:54 UTC, lauramaxwell approved these changes

2024-07-26 16:55 UTC, merged