Add Nickname to report header and fix `RunQuery` bug
Gilead-BioStats/gsm pull request #1915
Opened 2024-10-28 14:32 UTC by lauramaxwell

## Overview

Adds nickname to report header (when present) and fixes a bug that caused errors in RunQuery Dates outside of `ApplySpec()`

## Test Notes/Sample Code

Run example 3.2 in `inst/examples/3_ReportingWorkflow.R`

## Connected Issues

- Closes #1878
- Closes #1914

2024-11-04 16:24 UTC, jonthegeek commented
Merged main to pick up #1923.

2024-11-04 16:28 UTC, jonthegeek commented
Confirmed that this closes #1925!

2024-11-04 16:31 UTC, jonthegeek approved these changes
Looks great! I'm approving this from the context of the issue I was having (#1925, which was a duplicate of #1914, evidently), but I didn't dig into #1878.

2024-11-04 16:51 UTC, samussiah requested changes
Looks good @lauramaxwell!  Minor tweak for consistency, otherwise good to go!

2024-11-04 16:51 UTC, samussiah commented on R/Report_Setup.R
> +                              glue::glue('{output$lStudy$studyid} ({output$lStudy$nickname})')
```suggestion
                              glue::glue('{output$StudyID} ({output$lStudy$nickname})')
```

2024-11-04 16:51 UTC, samussiah commented on R/Report_Setup.R
> +                              glue::glue('{output$lStudy$studyid} ({output$lStudy$nickname})')
For consistency - not sure if there's a meaningful distinction between the two.

2024-11-04 19:31 UTC, lauramaxwell commented
> Looks good @lauramaxwell! Minor tweak for consistency, otherwise good to go!

updated this minor tweak!

2024-11-07 14:58 UTC, samussiah approved these changes
Perf.

2024-11-07 14:58 UTC, merged